name: Build and Test
on:
  push:
    branches: [ 'master', '1.6.x' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Build and test with maven
        run: mvn test -Dtest=!EntityLoaderBehaviorTest -DfailIfNoTests=false --no-transfer-progress -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
