name: Build and Test Selected Tests
on:
  workflow_dispatch:
    inputs:
      test-class-names:
        required: true
        description: Test classnames
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - name: Build and test with maven
        run: mvn test -B -DfailIfNoTests=false -Dtest={{test-class-names}}
